import {
  ADMIN_BOOKING_STATUS_OPTIONS,
  ADMIN_STATUS_OPTIONS,
  type AdminListSectionConfig,
} from '@/consts/adminSections';

export const ADMIN_EVENTS_CONFIG: AdminListSectionConfig = {
  sectionKey: 'events',
  titleKey: 'admin.events.title',
  descriptionKey: 'admin.events.description',
  breadcrumbsKey: 'admin.events.breadcrumbs',
  createLabelKey: 'admin.actions.createEvent',
  exportLabelKey: 'admin.actions.exportCsv',
  searchPlaceholderKey: 'admin.filters.searchEvent',
  searchFields: ['title', 'location', 'description'],
  hasStatusFilter: true,
  statusOptions: ADMIN_STATUS_OPTIONS,
  fields: [
    { name: 'title', labelKey: 'admin.fields.title', type: 'text', required: true },
    { name: 'date', labelKey: 'admin.fields.date', type: 'date', required: true },
    { name: 'location', labelKey: 'admin.fields.location', type: 'text', required: true },
    {
      name: 'status',
      labelKey: 'admin.fields.status',
      type: 'select',
      required: true,
      options: ADMIN_STATUS_OPTIONS,
    },
    { name: 'imageUrl', labelKey: 'admin.fields.imageUrl', type: 'url', required: true },
    { name: 'description', labelKey: 'admin.fields.description', type: 'textarea' },
  ],
  defaultValues: {
    title: '',
    date: '',
    location: '',
    status: 'draft',
    imageUrl: '',
    description: '',
  },
  getDetailTitle: (record) => String(record.title ?? ''),
  getDetailMeta: (record) => String(record.id ?? ''),
  getImageUrl: (record) => String(record.imageUrl ?? ''),
  tableColumns: ['detail', 'date', 'location', 'status'],
};

export const ADMIN_SERVICES_CONFIG: AdminListSectionConfig = {
  sectionKey: 'services',
  titleKey: 'admin.services.title',
  descriptionKey: 'admin.services.description',
  breadcrumbsKey: 'admin.services.breadcrumbs',
  createLabelKey: 'admin.actions.createItem',
  exportLabelKey: 'admin.actions.exportCsv',
  searchPlaceholderKey: 'admin.filters.searchTitle',
  searchFields: ['title', 'description'],
  hasStatusFilter: true,
  statusOptions: ADMIN_STATUS_OPTIONS,
  fields: [
    { name: 'title', labelKey: 'admin.fields.title', type: 'text', required: true },
    { name: 'description', labelKey: 'admin.fields.description', type: 'textarea', required: true },
    { name: 'imageUrl', labelKey: 'admin.fields.imageUrl', type: 'url', required: true },
    { name: 'iconKey', labelKey: 'admin.fields.iconKey', type: 'text', required: true },
    {
      name: 'status',
      labelKey: 'admin.fields.status',
      type: 'select',
      required: true,
      options: ADMIN_STATUS_OPTIONS,
    },
  ],
  defaultValues: {
    title: '',
    description: '',
    imageUrl: '',
    iconKey: 'wedding',
    status: 'draft',
  },
  getDetailTitle: (record) => String(record.title ?? ''),
  getDetailMeta: (record) => String(record.iconKey ?? ''),
  getImageUrl: (record) => String(record.imageUrl ?? ''),
  tableColumns: ['detail', 'status'],
};

export const ADMIN_GALLERY_CONFIG: AdminListSectionConfig = {
  sectionKey: 'gallery',
  titleKey: 'admin.gallery.title',
  descriptionKey: 'admin.gallery.description',
  breadcrumbsKey: 'admin.gallery.breadcrumbs',
  createLabelKey: 'admin.actions.createItem',
  exportLabelKey: 'admin.actions.exportCsv',
  searchPlaceholderKey: 'admin.filters.searchTitle',
  searchFields: ['title', 'category'],
  hasStatusFilter: true,
  statusOptions: ADMIN_STATUS_OPTIONS,
  fields: [
    { name: 'title', labelKey: 'admin.fields.title', type: 'text', required: true },
    { name: 'category', labelKey: 'admin.fields.category', type: 'text', required: true },
    { name: 'imageUrl', labelKey: 'admin.fields.imageUrl', type: 'url', required: true },
    {
      name: 'status',
      labelKey: 'admin.fields.status',
      type: 'select',
      required: true,
      options: ADMIN_STATUS_OPTIONS,
    },
  ],
  defaultValues: {
    title: '',
    category: '',
    imageUrl: '',
    status: 'draft',
  },
  getDetailTitle: (record) => String(record.title ?? ''),
  getDetailMeta: (record) => String(record.category ?? ''),
  getImageUrl: (record) => String(record.imageUrl ?? ''),
  tableColumns: ['detail', 'category', 'status'],
};

export const ADMIN_TESTIMONIALS_CONFIG: AdminListSectionConfig = {
  sectionKey: 'testimonials',
  titleKey: 'admin.testimonials.title',
  descriptionKey: 'admin.testimonials.description',
  breadcrumbsKey: 'admin.testimonials.breadcrumbs',
  createLabelKey: 'admin.actions.createItem',
  exportLabelKey: 'admin.actions.exportCsv',
  searchPlaceholderKey: 'admin.filters.searchClient',
  searchFields: ['clientName', 'eventType', 'quote'],
  hasStatusFilter: true,
  statusOptions: ADMIN_STATUS_OPTIONS,
  fields: [
    { name: 'clientName', labelKey: 'admin.fields.clientName', type: 'text', required: true },
    { name: 'eventType', labelKey: 'admin.fields.eventType', type: 'text', required: true },
    { name: 'quote', labelKey: 'admin.fields.quote', type: 'textarea', required: true },
    { name: 'rating', labelKey: 'admin.fields.rating', type: 'number', required: true },
    { name: 'avatarUrl', labelKey: 'admin.fields.avatarUrl', type: 'url' },
    {
      name: 'status',
      labelKey: 'admin.fields.status',
      type: 'select',
      required: true,
      options: ADMIN_STATUS_OPTIONS,
    },
  ],
  defaultValues: {
    clientName: '',
    eventType: '',
    quote: '',
    rating: 5,
    avatarUrl: '',
    status: 'draft',
  },
  getDetailTitle: (record) => String(record.clientName ?? ''),
  getDetailMeta: (record) => String(record.eventType ?? ''),
  getImageUrl: (record) => String(record.avatarUrl ?? ''),
  tableColumns: ['detail', 'rating', 'status'],
};

export const ADMIN_BOOKINGS_CONFIG: AdminListSectionConfig = {
  sectionKey: 'bookings',
  titleKey: 'admin.bookings.title',
  descriptionKey: 'admin.bookings.description',
  breadcrumbsKey: 'admin.bookings.breadcrumbs',
  createLabelKey: 'admin.actions.createBooking',
  exportLabelKey: 'admin.actions.exportCsv',
  searchPlaceholderKey: 'admin.filters.searchClient',
  searchFields: ['clientName', 'email', 'serviceType'],
  hasStatusFilter: true,
  statusOptions: ADMIN_BOOKING_STATUS_OPTIONS,
  fields: [
    { name: 'clientName', labelKey: 'admin.fields.clientName', type: 'text', required: true },
    { name: 'email', labelKey: 'admin.fields.email', type: 'text', required: true },
    { name: 'eventDate', labelKey: 'admin.fields.eventDate', type: 'date', required: true },
    { name: 'serviceType', labelKey: 'admin.fields.serviceType', type: 'text', required: true },
    {
      name: 'status',
      labelKey: 'admin.fields.status',
      type: 'select',
      required: true,
      options: ADMIN_BOOKING_STATUS_OPTIONS,
    },
  ],
  defaultValues: {
    clientName: '',
    email: '',
    eventDate: '',
    serviceType: '',
    status: 'pending',
  },
  getDetailTitle: (record) => String(record.clientName ?? ''),
  getDetailMeta: (record) => String(record.serviceType ?? ''),
  tableColumns: ['detail', 'date', 'email', 'status'],
};

export const ADMIN_CODE_TABLE_CONFIG: AdminListSectionConfig = {
  sectionKey: 'codeTable',
  titleKey: 'admin.codeTable.title',
  descriptionKey: 'admin.codeTable.description',
  breadcrumbsKey: 'admin.codeTable.breadcrumbs',
  createLabelKey: 'admin.actions.createItem',
  exportLabelKey: 'admin.actions.exportCsv',
  searchPlaceholderKey: 'admin.filters.searchCode',
  searchFields: ['code', 'label', 'category', 'description'],
  hasStatusFilter: false,
  fields: [
    { name: 'code', labelKey: 'admin.fields.code', type: 'text', required: true },
    { name: 'label', labelKey: 'admin.fields.label', type: 'text', required: true },
    { name: 'category', labelKey: 'admin.fields.category', type: 'text', required: true },
    { name: 'description', labelKey: 'admin.fields.description', type: 'textarea', required: true },
  ],
  defaultValues: {
    code: '',
    label: '',
    category: '',
    description: '',
  },
  getDetailTitle: (record) => String(record.label ?? ''),
  getDetailMeta: (record) => String(record.code ?? ''),
  tableColumns: ['detail', 'code', 'category'],
};
